export enum SignalType {
  BUY = 'BUY',
  SELL = 'SELL',
  HOLD = 'HOLD'
}

export enum MediaType {
  NEWS = 'NEWS',
  VIDEO = 'VIDEO',
  PDF = 'PDF',
  SOCIAL = 'SOCIAL'
}

export interface Ticker {
  code: string;
  name: string;
  price: number;
  change: number;
  changePct: number;
  volume: number;
  sector: string;
}

export interface MediaSource {
  id: string;
  type: MediaType;
  title: string;
  url?: string;
  timestamp: string;
  snippet: string;
  sentiment: 'POSITIVE' | 'NEGATIVE' | 'NEUTRAL';
  relevanceScore: number; // 0 to 1
  // Specifics for video/audio
  startTime?: string; 
}

export interface EnsembleModelOutput {
  lightGBM: number; // Probability
  transformer: number; // Probability
  sentimentAnalysis: number; // Sentiment Score
  combinedScore: number;
}

export interface TradeSignal {
  id: string;
  ticker: string;
  type: SignalType;
  confidence: number; // 0 to 100
  timestamp: string;
  entryPrice: number;
  stopLoss: number;
  targetPrice: number;
  predictedReturn: number;
  reasoning: string; // Generated by LLM
  sources: MediaSource[]; // RAG citations
  technicalIndicators: {
    rsi: number;
    ema20: number;
    vwap: number;
  };
  ensembleDetails: EnsembleModelOutput;
  liquidityWarning?: boolean;
}

export interface BacktestConfig {
  initialCapital: number;
  startDate: string;
  endDate: string;
  strategy: string;
  commission: number; // percent
  tax: number; // percent
}

export interface BacktestResult {
  totalReturn: number;
  sharpeRatio: number;
  maxDrawdown: number;
  winRate: number;
  equityCurve: { date: string; equity: number }[];
  trades: number;
}

export interface IngestionTask {
  id: string;
  source: string;
  type: MediaType;
  status: 'PENDING' | 'PROCESSING' | 'COMPLETED' | 'FAILED';
  progress: number;
  details: string;
}

export interface TradeLog {
  id: string;
  signalId?: string;
  ticker: string;
  type: 'BUY' | 'SELL';
  price: number;
  lots: number;
  date: string;
  notes: string;
}