
import { TradeLog, IngestionTask, TradeSignal } from '../types';

const API_BASE_URL = 'http://localhost:8000';

export const ApiClient = {
  /**
   * Fetch daily recommendations generated by the backend
   */
  getDailyRecommendations: async (): Promise<TradeSignal[]> => {
    try {
      const response = await fetch(`${API_BASE_URL}/recommendations/daily`);
      if (!response.ok) throw new Error('Failed to fetch recommendations');
      return await response.json();
    } catch (error) {
      console.error("API Error (Mocking response for prototype):", error);
      return []; // Return mock data in real app fallback
    }
  },

  /**
   * Log a manual trade to the backend for active learning
   */
  logTrade: async (trade: TradeLog): Promise<{id: string, status: string}> => {
    try {
      const response = await fetch(`${API_BASE_URL}/trades`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(trade)
      });
      return await response.json();
    } catch (error) {
      console.log("Mocking successful trade log");
      return { id: "mock-log-id", status: "logged" };
    }
  },

  /**
   * Trigger an ingestion task
   */
  triggerIngestion: async (sourceType: string, url: string): Promise<{taskId: string}> => {
    const response = await fetch(`${API_BASE_URL}/ingest`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ source_type: sourceType, url_or_path: url })
    });
    return await response.json();
  },

  /**
   * Run backtest simulation
   */
  runBacktest: async (config: any) => {
    const response = await fetch(`${API_BASE_URL}/backtest/run`, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(config)
    });
    return await response.json();
  }
};
